const TASKS = [
  ["夜ごはん手伝い", 100], ["夜ごはん手伝い途中まで", 50], ["食器洗い", 100], ["ねこ犬トイレ掃除", 50], ["ねこ犬ごはん", 10], ["洗濯物干す（2人で）", 50], ["洗濯物たたむ（2人で）", 50], ["洗濯物干す（1人で）", 100], ["洗濯物たたむ（1人で）", 100], ["牛乳パックカット10個", 50], ["かたたたき", 50], ["掃除機", 100]
].map(([name, price], index) => ({ id:String(index + 1), name, price }));
const DAILY_LIMIT = 100;
const STORAGE_KEY = "otetsudai-chokin-records";
let records = JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]");
const todayKey = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tokyo" }).format(new Date());
const $ = (selector) => document.querySelector(selector);
const yen = (amount) => `${amount.toLocaleString("ja-JP")}円`;
const todayRecords = () => records.filter((record) => record.date === todayKey);
const isTask = (record) => !record.kind || record.kind === "task";
const approvedTaskAmount = (date) => Math.min(records.filter((record) => record.date === date && isTask(record) && record.status === "approved").reduce((sum, record) => sum + record.price, 0), DAILY_LIMIT);
const approvedToday = () => approvedTaskAmount(todayKey);
const reservedToday = () => todayRecords().filter((record) => isTask(record) && (record.status === "approved" || record.status === "pending")).reduce((sum, record) => sum + record.price, 0);
const totalAmount = () => [...new Set(records.filter((record) => isTask(record)).map((record) => record.date))].reduce((sum, date) => sum + approvedTaskAmount(date), 0) + records.filter((record) => record.status === "approved" && record.kind === "gift").reduce((sum, record) => sum + record.price, 0);
const spentAmount = () => records.filter((record) => record.status === "approved" && record.kind === "spend").reduce((sum, record) => sum + record.price, 0);
const balanceAmount = () => totalAmount() - spentAmount();
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(records)); }
function formatDate(date) { return new Intl.DateTimeFormat("ja-JP", { month:"long", day:"numeric", weekday:"short" }).format(date); }
function formatTime(value) { return new Intl.DateTimeFormat("ja-JP", { hour:"numeric", minute:"2-digit" }).format(new Date(value)); }
function showToast(message) { const toast = $("#toast"); toast.textContent = message; toast.classList.add("is-visible"); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove("is-visible"), 2300); }
function renderSummary() { const reserved = reservedToday(); $("#todayAmount").textContent = approvedToday(); $("#balanceAmount").textContent = balanceAmount(); $("#totalAmount").textContent = totalAmount(); $("#spentAmount").textContent = spentAmount(); $("#dailyProgress").style.width = `${Math.min(reserved / DAILY_LIMIT * 100, 100)}%`; $("#remainingLabel").textContent = reserved >= DAILY_LIMIT ? "今日の上限に到達しました" : `あと${yen(DAILY_LIMIT - reserved)}まで`; $("#taskCount").textContent = `${Math.min(reserved, DAILY_LIMIT)} / ${DAILY_LIMIT}円`; $("#pendingCount").textContent = `${todayRecords().filter((record) => record.status === "pending").length}件`; }
function renderTasks() { $("#taskList").innerHTML = TASKS.map((task) => `<article class="task-item"><div><div class="task-name">${task.name}</div><span class="task-note">何回でも申請できるよ</span></div><div class="task-action"><span class="task-price">${yen(task.price)}</span><button class="task-button" data-task-id="${task.id}">申請する</button></div></article>`).join(""); document.querySelectorAll(".task-button").forEach((button) => button.addEventListener("click", () => submitTask(button.dataset.taskId))); }
function statusLabel(status) { return { pending:"確認まち", approved:"承認済み", rejected:"却下" }[status]; }
function activityMarkup(record) { const sign = record.kind === "spend" ? "-" : "+"; return `<div class="activity-item"><div><div class="activity-name">${record.name}</div><div class="activity-meta">${formatTime(record.createdAt)} ・ ${sign}${yen(record.price)}</div></div><span class="status status--${record.status}">${statusLabel(record.status)}</span></div>`; }
function renderChildHistory() { const items = todayRecords().sort((a, b) => b.createdAt.localeCompare(a.createdAt)); $("#childHistory").innerHTML = items.length ? items.map(activityMarkup).join("") : '<div class="empty-state">おてつだいをすると、ここに記録されるよ。</div>'; }
function renderParent() { const pending = records.filter((record) => record.status === "pending").sort((a, b) => b.createdAt.localeCompare(a.createdAt)); $("#parentRequests").innerHTML = pending.length ? pending.map((record) => `<article class="request-card"><div class="request-main"><div><div class="request-name">${record.name}</div><div class="request-time">${formatTime(record.createdAt)} に申請</div></div><span class="request-price">${yen(record.price)}</span></div><div class="request-actions"><button class="approve-button" data-action="approved" data-record-id="${record.id}">承認する</button><button class="reject-button" data-action="rejected" data-record-id="${record.id}">却下する</button></div></article>`).join("") : '<div class="empty-state">新しい申請はありません。</div>'; $("#parentHistory").innerHTML = records.length ? records.slice().sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(activityMarkup).join("") : '<div class="empty-state">まだ記録がありません。</div>'; document.querySelectorAll("[data-record-id]").forEach((button) => button.addEventListener("click", () => updateRecord(button.dataset.recordId, button.dataset.action))); }
function render() { renderSummary(); renderTasks(); renderChildHistory(); renderParent(); }
function submitTask(taskId) { const task = TASKS.find((item) => item.id === taskId); if (!task) return; records.push({ id:crypto.randomUUID(), kind:"task", taskId:task.id, name:task.name, price:task.price, status:"pending", date:todayKey, createdAt:new Date().toISOString() }); save(); render(); showToast("申請したよ。おかあさんの確認を待ってね"); }
function submitSpend(event) { event.preventDefault(); const amount = Number($("#spendAmount").value); const note = $("#spendNote").value.trim(); if (!amount || amount < 1 || !note) return showToast("金額と内容を入力してね"); if (amount > balanceAmount()) return showToast("使えるおこづかいが足りません"); records.push({ id:crypto.randomUUID(), kind:"spend", name:`使用：${note}`, price:amount, status:"approved", date:todayKey, createdAt:new Date().toISOString() }); save(); event.target.reset(); render(); showToast(`${yen(amount)}使ったことを記録しました`); }
function submitGift(event) { event.preventDefault(); const amount = Number($("#giftAmount").value); const note = $("#giftNote").value.trim(); if (!amount || amount < 1 || !note) return showToast("金額とメモを入力してね"); records.push({ id:crypto.randomUUID(), kind:"gift", name:`お母さんから：${note}`, price:amount, status:"approved", date:todayKey, createdAt:new Date().toISOString() }); save(); event.target.reset(); render(); showToast(`${yen(amount)}渡しました`); }
function updateRecord(recordId, status) { records = records.map((record) => record.id === recordId ? { ...record, status } : record); save(); render(); showToast(status === "approved" ? "承認しました" : "却下しました"); }
$("#todayLabel").textContent = formatDate(new Date());
$("#spendForm").addEventListener("submit", submitSpend); $("#giftForm").addEventListener("submit", submitGift);
$("[data-role=child]").addEventListener("click", () => switchRole("child")); $("[data-role=parent]").addEventListener("click", () => switchRole("parent"));
function switchRole(role) { $("#childView").classList.toggle("is-hidden", role !== "child"); $("#parentView").classList.toggle("is-hidden", role !== "parent"); $("[data-role=child]").classList.toggle("is-active", role === "child"); $("[data-role=parent]").classList.toggle("is-active", role === "parent"); $("#greeting").textContent = role === "child" ? "今日のおてつだい" : "申請をチェック"; }
render();